spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/haibincoast/cloud_haoyi_study.git
          search-paths: config-repo
server:
  port: 12000