spring:
  application:
    name: eureka_server
#  profiles:
#    active: peer1,peer2
server:
  port: 10000
eureka:
  instance:
    appname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.appname}:${server.port}/eureka