spring:
  application:
    name: eureka_server
server:
  port: 10001
eureka:
  instance:
    appname: peer1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://peer2:10002/eureka/