spring:
  application:
    name: eureka_server
server:
  port: 10002
eureka:
  instance:
    appname: peer2
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://peer1:10001/eureka/